package chatrole

import (
	"fmt"
	"strings"
)

type ChatRole struct {
	Code        string
	Description string
}

var (
	System = ChatRole{
		Code:        "system",
		Description: "Provides initial instructions or context to the assistant.",
	}
	User = ChatRole{
		Code:        "user",
		Description: "Represents the user input in a conversation.",
	}
	Assistant = ChatRole{
		Code:        "assistant",
		Description: "Represents responses generated by the assistant.",
	}
	Tool = ChatRole{
		Code:        "tool",
		Description: "Represents messages generated by tool function calls.",
	}
)

var AllChatRoles = map[string]*ChatRole{
	System.Code:    &System,
	User.Code:      &User,
	Assistant.Code: &Assistant,
	Tool.Code:      &Tool,
}

func Resolve(code string) (*ChatRole, error) {
	if rol, ok := AllChatRoles[code]; ok {
		return rol, nil
	}

	return nil, fmt.Errorf("unknown value '%v'", code)
}

func JoinCodes(sep string) string {
	var codes []string
	for _, rol := range AllChatRoles {
		codes = append(codes, rol.Code)
	}

	return strings.Join(codes, sep)
}
