package purpose

import "fmt"

type Purpose struct {
	Code        string
	Description string
}

var (
	FineTune = Purpose{
		Code:        "fine-tune",
		Description: "Used to upload files for fine-tuning models.",
	}
	FineTuneResults = Purpose{
		Code:        "fine-tune-results",
		Description: "Used to upload results of fine-tuning jobs.",
	}
	Assistants = Purpose{
		Code:        "assistants",
		Description: "Used to upload files for the Assistants API.",
	}
	AssistantsOutput = Purpose{
		Code:        "assistants_output",
		Description: "Used to upload files generated by assistants.",
	}
)

var AllPurposes = map[string]*Purpose{
	FineTune.Code:         &FineTune,
	FineTuneResults.Code:  &FineTuneResults,
	Assistants.Code:       &Assistants,
	AssistantsOutput.Code: &AssistantsOutput,
}

func Resolve(code string) (*Purpose, error) {
	if code == "" {
		return &FineTune, nil
	}

	if prp, ok := AllPurposes[code]; ok {
		return prp, nil
	}

	return nil, fmt.Errorf("purpose: unknown value %q", code)
}
